name: CI
on:
    pull_request:
    push:
        branches:
            - main
jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup bun
              uses: oven-sh/setup-bun@v1
              with:
                  bun-version: 1.1.18
            - name: Install dependencies
              run: bun install --frozen-lockfile
            - name: Build Project
              run: bun run build
            - name: Archive build output
              uses: actions/upload-artifact@v4
              with:
                  name: build-output
                  path: .vercel/